variables:
- group: ServiceConnection-PRD1
- name: docker.imageName
  value: 'subsidiaryupload'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'subsidiaryuploadrepository'
- name: serviceName
  value: 'PRDRWDWEBFA1408'
